//admin login
export const USER_LOGIN = 'USER_LOGIN';
export const FORGET_SELLER = 'FORGET_SELLER';
export const RESET_PASSWORD_SELLER = 'RESET_PASSWORD_SELLER';
export const USERS_ERROR = 'USERS_ERROR';
export const USERS_LOGOUT = 'USERS_LOGOUT';
export const USER_LOADING = 'USER_LOADING';

// category master
export const FETCH_CATG_LIST = 'FETCH_CATG_LIST';
export const FETCH_CATG_REQ = 'FETCH_CATG_REQ';
export const FETCH_CATG_UPDATE = 'FETCH_CATG_UPDATE';
export const FETCH_CATG_DETAIL = 'FETCH_CATG_DETAIL';
export const FETCH_CATG_ADD = 'FETCH_CATG_ADD';
export const FETCH_CATG_ERROR = 'FETCH_CATG_ERROR';

//subcategory master
export const FETCH_SUBCATG_LIST = 'FETCH_SUBCATG_LIST';
export const FETCH_SUBCATG_REQ = 'FETCH_SUBCATG_REQ';
export const FETCH_SUBCATG_ADD = 'FETCH_SUBCATG_ADD';
export const FETCH_SUBCATG_ERROR = 'FETCH_SUBCATG_ERROR';

//UOM master
export const FETCH_UOM_LIST = 'FETCH_UOM_LIST';
export const FETCH_UOM_REQ = 'FETCH_UOM_REQ';
export const FETCH_UOM_ERROR = 'FETCH_UOM_ERROR';

//PORT master
export const FETCH_PORT_LIST = 'FETCH_PORT_LIST';
export const FETCH_PORT_REQ = 'FETCH_PORT_REQ';
export const FETCH_PORT_ERROR = 'FETCH_PORT_ERROR';

//BRAND master
export const FETCH_BRAND_LIST = 'FETCH_BRAND_LIST';
export const FETCH_BRAND_REQ = 'FETCH_BRAND_REQ';
export const FETCH_BRAND_ERROR = 'FETCH_BRAND_ERROR';

//BAGS master
export const FETCH_BAG_LIST = 'FETCH_BAG_LIST';
export const FETCH_BAG_REQ = 'FETCH_BAG_REQ';
export const FETCH_BAG_ERROR = 'FETCH_BAG_ERROR';

//product master
export const FETCH_PRODUCTIMPORT_LIST = 'FETCH_PRODUCTIMPORT_LIST';
export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const FETCH_PRODUCT_REQ = 'FETCH_PRODUCT_REQ';
export const FETCH_PRODUCT_ADD = 'FETCH_PRODUCT_ADD';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FETCH_PRODUCT_SELLER_LIST = 'FETCH_PRODUCT_SELLER_LIST';
export const FETCH_PRODUCT_DEPARTMENT = 'FETCH_PRODUCT_DEPARTMENT';

//seller master
export const FETCH_SELLER_LIST = 'FETCH_SELLER_LIST';
export const FETCH_SELLERIMPORT_LIST = 'FETCH_SELLERIMPORT_LIST';
export const FETCH_SELLER_REQ = 'FETCH_SELLER_REQ';
export const FETCH_SELLER_DETAIL = 'FETCH_SELLER_DETAIL';
export const FETCH_SELLER_ADD = 'FETCH_SELLER_ADD';
export const FETCH_SELLER_ERROR = 'FETCH_SELLER_ERROR';

//seller pincode master
export const FETCH_SELLERPINCODE_LIST = 'FETCH_SELLERPINCODE_LIST';
export const FETCH_SELLERPINCODEIMPORT_LIST = 'FETCH_SELLERPINCODEIMPORT_LIST';
export const FETCH_SELLERPINCODE_REQ = 'FETCH_SELLERPINCODE_REQ';
export const FETCH_SELLERPINCODE_ADD = 'FETCH_SELLERPINCODE_ADD';
export const FETCH_SELLERPINCODE_ERROR = 'FETCH_SELLERPINCODE_ERROR';

//seller product master
export const FETCH_SELLERPRODUCT_LIST = 'FETCH_SELLERPRODUCT_LIST';
export const FETCH_SELLERPRODUCTADMIN_LIST = 'FETCH_SELLERPRODUCTADMIN_LIST';
export const FETCH_SELLERPRODUCTIMPORT_LIST = 'FETCH_SELLERPRODUCTIMPORT_LIST';
export const FETCH_SELLERPRODUCT_REQ = 'FETCH_SELLERPRODUCT_REQ';
export const FETCH_SELLERPRODUCT_ADD = 'FETCH_SELLERPRODUCT_ADD';
export const FETCH_SELLERPRODUCT_ERROR = 'FETCH_SELLERPRODUCT_ERROR';
export const FETCH_SELLERPRODUCT_DET = 'FETCH_SELLERPRODUCT_DET';

//country master
export const FETCH_COUNTRY_LIST = 'FETCH_COUNTRY_LIST';
export const FETCH_COUNTRY_REQ = 'FETCH_COUNTRY_REQ';
export const FETCH_COUNTRY_ADD = 'FETCH_COUNTRY_ADD';
export const FETCH_COUNTRY_ERROR = 'FETCH_COUNTRY_ERROR';
export const FETCH_COUNTRY_DETAIL = 'FETCH_COUNTRY_DETAIL';
export const FETCH_COUNTRY_UPDATE = 'FETCH_COUNTRY_UPDATE';

//state master
export const FETCH_STATE_LIST = 'FETCH_STATE_LIST';
export const FETCH_STATE_UPDATE = 'FETCH_STATE_UPDATE';
export const FETCH_STATE_REQ = 'FETCH_STATE_REQ';
export const FETCH_STATE_ADD = 'FETCH_STATE_ADD';
export const FETCH_STATE_DETAIL = 'FETCH_STATE_DETAIL';
export const FETCH_STATE_ERROR = 'FETCH_STATE_ERROR';

//city master
export const FETCH_CITY_LIST = 'FETCH_CITY_LIST';
export const FETCH_CITY_REQ = 'FETCH_CITY_REQ';
export const FETCH_CITY_ERROR = 'FETCH_CITY_ERROR';
export const FETCH_CITY_ADD = 'FETCH_CITY_ADD';
export const FETCH_CITY_UPDATE = 'FETCH_CITY_UPDATE';
export const FETCH_CITY_DETAIL = 'FETCH_CITY_DETAIL';

//city master
export const FETCH_CANCELLATION_LIST = 'FETCH_CANCELLATION_LIST';
export const FETCH_CANCELLATION_REQ = 'FETCH_CANCELLATION_REQ';
export const FETCH_CANCELLATION_ADD = 'FETCH_CANCELLATION_ADD';
export const FETCH_CANCELLATION_DET = 'FETCH_CANCELLATION_DET';
export const FETCH_CANCELLATION_ERROR = 'FETCH_CANCELLATION_ERROR';

//delivery master
export const FETCH_DELIVERYBOY_LIST = 'FETCH_DELIVERYBOY_LIST';
export const FETCH_DELIVERYBOY_REQ = 'FETCH_DELIVERYBOY_REQ';
export const FETCH_DELIVERYBOY_ADD = 'FETCH_DELIVERYBOY_ADD';
export const FETCH_DELIVERYBOY_DET = 'FETCH_DELIVERYBOY_DET';
export const FETCH_DELIVERYBOY_ERROR = 'FETCH_DELIVERYBOY_ERROR';

//pincode master
export const FETCH_PINCODE_LIST = 'FETCH_PINCODE_LIST';
export const FETCH_PINCODEIMPORT_LIST = 'FETCH_PINCODEIMPORT_LIST';
export const FETCH_PINCODE_REQ = 'FETCH_PINCODE_REQ';
export const FETCH_PINCODE_ADD = 'FETCH_PINCODE_ADD';
export const FETCH_PINCODE_UPDATE = 'FETCH_PINCODE_UPDATE';
export const FETCH_PINCODE_DETAIL = 'FETCH_PINCODE_DETAIL';
export const FETCH_PINCODE_ERROR = 'FETCH_PINCODE_ERROR';

//home master topdeals
export const FETCH_TOPDEAL_LIST = 'FETCH_TOPDEAL_LIST';
export const FETCH_TOPDEALIMPORT_LIST = 'FETCH_TOPDEALIMPORT_LIST';
export const FETCH_TOPDEAL_REQ = 'FETCH_TOPDEAL_REQ';
export const FETCH_TOPDEAL_ADD = 'FETCH_TOPDEAL_ADD';
export const FETCH_TOPDEAL_ERROR = 'FETCH_TOPDEAL_ERROR';

//home master topcategory
export const FETCH_TOPCAT_LIST = 'FETCH_TOPCAT_LIST';
export const FETCH_TOPCAT_REQ = 'FETCH_TOPCAT_REQ';
export const FETCH_TOPCAT_ADD = 'FETCH_TOPCAT_ADD';
export const FETCH_TOPCAT_IMPORT = 'FETCH_TOPCAT_IMPORT';
export const FETCH_TOPCAT_ERROR = 'FETCH_TOPCAT_ERROR';

//home master newArrivals
export const FETCH_NEWARRIVAL_LIST = 'FETCH_NEWARRIVAL_LIST';
export const FETCH_NEWARRIVAL_REQ = 'FETCH_NEWARRIVAL_REQ';
export const FETCH_NEWARRIVAL_ADD = 'FETCH_NEWARRIVAL_ADD';
export const FETCH_NEWARRIVAL_IMPORT = 'FETCH_NEWARRIVAL_IMPORT';
export const FETCH_NEWARRIVAL_ERROR = 'FETCH_NEWARRIVAL_ERROR';

//coupon master
export const FETCH_COUPON_LIST = 'FETCH_COUPON_LIST';
export const FETCH_COUPON_REQ = 'FETCH_COUPON_REQ';
export const FETCH_COUPON_ADD = 'FETCH_COUPON_ADD';
export const FETCH_COUPON_ERROR = 'FETCH_COUPON_ERROR';
export const FETCH_COUPON_DET = 'FETCH_COUPON_DET';
export const FETCH_COUPON_UPDATE = 'FETCH_COUPON_UPDATE';

export const FETCH_MEDIA_REQ = 'FETCH_MEDIA_REQ';
export const FETCH_MEDIA_ADD = 'FETCH_MEDIA_ADD';
export const FETCH_MEDIA_ERROR = 'FETCH_MEDIA_ERROR';

export const FETCH_CUSTOMER_REQ = 'FETCH_CUSTOMER_REQ';
export const FETCH_CUSTOMER_LIST = 'FETCH_CUSTOMER_LIST';
export const FETCH_CUSTOMER_ERROR = 'FETCH_CUSTOMER_ERROR';
export const FETCH_GUEST_LIST = 'FETCH_GUEST_LIST';

export const FETCH_ORDER_REQ = 'FETCH_ORDER_REQ';
export const FETCH_ORDER_LIST = 'FETCH_ORDER_LIST';
export const FETCH_ORDER_ERROR = 'FETCH_ORDER_ERROR';
export const FETCH_ORDER_UPDATE = 'FETCH_ORDER_UPDATE';
export const FETCH_PREORDER_LIST = 'FETCH_PREORDER_LIST';
export const FETCH_ORDER_DET = 'FETCH_ORDER_DET';
export const FETCH_ORDER_DOWN = 'FETCH_ORDER_DOWN';

export const FETCH_REPORT_REQ = 'FETCH_REPORT_REQ';
export const FETCH_REPORT_LIST = 'FETCH_REPORT_LIST';
export const FETCH_REPORT_ERROR = 'FETCH_REPORT_ERROR';
export const FETCH_CONSUMER_FEEDBACK_LIST = 'FETCH_CONSUMER_FEEDBACK_LIST';

//NOTIFICATION MASTER
export const FETCH_NOT_REQ = 'FETCH_NOT_REQ';
export const FETCH_NOT_ERROR = 'FETCH_NOT_ERROR';
export const FETCH_TEMPLATE_LIST = 'FETCH_TEMPLATE_LIST';
export const FETCH_TEMPLATE_DETAIL = 'FETCH_TEMPLATE_DETAIL';
export const FETCH_LOGS = 'FETCH_LOGS';
export const CUSTOMER_LOGS = 'CUSTOMER_LOGS';

export const FETCH_TEMPLATE_TYPE_LIST = 'FETCH_TEMPLATE_TYPE_LIST';

//SELLER PAYTM
export const FETCH_PAY_ERROR = 'FETCH_PAY_ERROR';
export const SELLER_PAYTM_LIST = 'SELLER_PAYTM_LIST';
export const FETCH_SELLERPAY_REQ = 'FETCH_SELLERPAY_REQ';
export const SELLER_PAYTM_DETAIL = 'SELLER_PAYTM_DETAIL';

//USER MANAGMENT

export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_USERM_ERROR = 'FETCH_USERM_ERROR';
export const FETCH_USERM_REQ = 'FETCH_USERM_REQ';
export const FETCH_ADMIN_LIST = 'FETCH_ADMIN_LIST';
export const FETCH_POLICY = 'FETCH_POLICY';
export const FETCH_ASSIGNED_POLICY = 'FETCH_ASSIGNED_POLICY';

export const FETCH_PRODUCT_MEDIA_REQ = 'FETCH_PRODUCT_MEDIA_REQ';
export const FETCH_PRODUCT_MEDIA_LIST = 'FETCH_PRODUCT_MEDIA_LIST';
export const FETCH_PRODUCT_MEDIA_DETAILS = 'FETCH_PRODUCT_MEDIA_DETAILS';
export const FETCH_PRODUCT_MEDIA_ERROR = 'FETCH_PRODUCT_MEDIA_ERROR';
export const FETCH_ASSIGNED_PINCODES="FETCH_ASSIGNED_PINCODES";

//home master banner
export const FETCH_BANNER_MEDIA_LIST = 'FETCH_BANNER_MEDIA_LIST';
export const FETCH_BANNER_MEDIA_REQ = 'FETCH_BANNER_MEDIA_REQ';
export const FETCH_BANNER_MEDIA_DETAILS = 'FETCH_BANNER_MEDIA_DETAILS';
export const FETCH_BANNER_MEDIA_ERROR = 'FETCH_BANNER_MEDIA_ERROR';
export const FETCH_BANNER_ADD = 'FETCH_BANNER_ADD';
export const FETCH_BANNER_ERROR = 'FETCH_BANNER_ERROR';
export const FETCH_BANNER_IMPORT = 'FETCH_BANNER_IMPORT';
export const FETCH_BANNER_LIST = 'FETCH_BANNER_LIST';
export const FETCH_BANNER_REQ = 'FETCH_BANNER_REQ';
export const FETCH_PRODUCT_SKU='FETCH_PRODUCT_SKU';
export const FETCH_BANNER_GALLERY="FETCH_BANNER_GALLERY";

//KYC
export const BUSSINESS_LIST='BUSSINESS_LIST';
export const FETCH_BUSSINESS_ERROR='FETCH_BUSSINESS_ERROR';
export const FETCH_BUSSINESS_REQ='FETCH_BUSSINESS_REQ';
export const FETCH_BUSINESS_TYPE="FETCH_BUSINESS_TYPE";
export const FETCH_INTRESTED_CATEGORIES="FETCH_INTRESTED_CATEGORIES";

//CUSTOMER SELLER MAPPING
export const FETCH_SELLERCUS_REQ ="FETCH_SELLERCUS_REQ";
export const FETCH_SELLERCUS_LIST="FETCH_SELLERCUS_LIST";
export const FETCH_SELLERCUS_IMPORT="FETCH_SELLERCUS_IMPORT";
export const FETCH_SELLERCUS_ERROR="FETCH_SELLERCUS_ERROR";
export const SELLER_CUSTOMER_IMPORT="SELLER_CUSTOMER_IMPORT";
//SALESMAN
export const FETCH_SALES_REQ="FETCH_SALES_REQ";
export const FETCH_SALES_LIST="FETCH_SALES_LIST";
export const FETCH_SALES_ERROR="FETCH_SALES_ERROR";
export const IMPORT_ERROR_SALESMAN="IMPORT_ERROR_SALESMAN";
//BEAT
export const FETCH_BEAT_REQ="FETCH_BEAT_REQ";
export const FETCH_BEAT_LIST="FETCH_BEAT_LIST";
export const FETCH_BEAT_ERROR="FETCH_BEAT_ERROR";
export const FETCH_IMPORT_ERROR="FETCH_IMPORT_ERROR";
//BUSINESS LINE
export const FETCH_BUSINESS_LINE="FETCH_BUSINESS_LINE";

//DMS
export const DMS_ORDERS="DMS_ORDERS";
export const DMS_ERROR="DMS_ERROR";

export const OTP_REGISTERED="OTP_REGISTERED";